# fly.toml file generated for isseptafcked on 2022-11-26T15:45:29-05:00

app = "isseptafcked"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
#
# I'm normally a huge fan of UTC, but in this case setting a timezone and using the local time 
# makes more sense as SEPTA is in a single timezone, and so are all of the visitors to the website.
#
# (That, and this is quicker than fixing the date/time calls in the code.  Though I may opt to do that someday.)
#
TZ = "EST5EDT"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  #internal_port = 8080
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"


